### PR TITLE
fix: i18n:  en.ts, spelling

### PR DESCRIPTION
**Pull request by SergeCroise**
- ... error occu**rr**ed ...
- ... pre**ced**ence ...
- ... stre**tch**es ...
see merriam-webster:
https://www.merriam-webster.com/dictionary/stretches

### CODE REVIEW

**Comment by testower** [comment]
Thank you for your contribution!

**Comment by testower** [comment]
The code is not formatted according to prettier's formatting rule. Please run "npm run format" and re-submit.

**Comment by SergeCroise** [comment]
> Needs reformatting

hello @testower
thank you for your info,
if you agree, I would like to suppress the two lines on top of the file and the identifier MessagesKey

**Comment by testower** [comment]
Doesn't make any sense to me. What are you trying to achieve? Are you using this project?

**Comment by SergeCroise** [comment]
Indeed, does not make sense. I suggest to close this PR.

**Pull request closed without merging**
